export { default as HowPC } from './howpc/HowPC.jsx'
export { default as Footer } from './footer/Footer.jsx'
export { default as Header } from './header/Header.jsx'
export { default as Possibility } from './possibility/Possibility.jsx'
export { default as WhyPC } from './whypc/WhyPC.jsx'
